version: '3.1'
services:
    redis:
        image: 'redis:alpine'
        container_name: api_report_redis

    mysql:
        image: 'mysql:5.7'
        container_name: api_report_mysql
        working_dir: /code
        volumes:
            - '.:/code'
            - '../docker/mysql/db:/var/lib/mysql'
        environment:
            - MYSQL_ROOT_PASSWORD=toor
            - MYSQL_DATABASE=api_report
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
        ports:
            - '4001:3306'

    nginx:
        image: 'nginx:alpine'
        container_name: api_report_nginx
        working_dir: /code
        volumes:
            - '.:/code'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '4000:80'

    php-fpm:
        build: .
        container_name: api_report_php_fpm
        working_dir: /code
        volumes:
            - '.:/code'
            - './docker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'

    rabbitmq:
        image: rabbitmq:3.8-management
        container_name: 'api_report_rabbitmq'
        volumes:
            - './docker/rabbitmq/data/:/var/lib/rabbitmq'
            - './docker/rabbitmq/log/:/var/log/rabbitmq'
        ports:
            - 5672:5672
            - 15672:15672
